chore: Update iOS dependencies
flutter-ml/google_ml_kit_flutter pull request #693
Opened 2024-10-04 13:32 UTC by OutdatedGuy

fixes #669

## Changes
- Updates `GoogleMLKit` to [v7.0.0](https://developers.google.com/ml-kit/release-notes#september_30_2024) released on 30th September.
- Sets Minimum iOS Deployment Target to `15.5.0`

2024-10-06 06:19 UTC, fbernaly commented
@OutdatedGuy: thanks for your contributions, I am going to review your PR. Did you test the changes with the example app?

2024-10-06 06:27 UTC, fbernaly requested changes

2024-10-06 06:27 UTC, fbernaly commented on CHANGELOG.md
> +## 2024-10-04
Change date to 2024-10-07

2024-10-06 06:28 UTC, fbernaly commented
Do we need to bump all the dependencies from iOS 12 to 15.5.0?

2024-10-06 06:32 UTC, fbernaly requested changes

2024-10-06 06:32 UTC, fbernaly commented on AUTHORS
> +Om Phatak <everythingoutdated@gmail.com>
Thanks for your contributions. Once this PR is merged, you will be listed as a contributor as many others have done. This file is only for those who have written a plug-in from scratch: a whole new ML kit feature/API from scratch. Please, revert the changes in this file. Thanks.

2024-10-06 10:53 UTC, OutdatedGuy commented
> @OutdatedGuy: thanks for your contributions, I am going to review your PR. Did you test the changes with the example app?

Yeah, I have tested it on iOS simulator and a real device. Everything seems to be working fine.

2024-10-06 10:57 UTC, OutdatedGuy commented
> Do we need to bump all the dependencies from iOS 12 to 15.5.0?

Most likely, as the [official release notes](https://developers.google.com/ml-kit/release-notes#september_30_2024) mentioned the minimum support change.

I tried running few plugins on iOS 13, but got error due to minimum support incompatible.

2024-10-07 02:51 UTC, vietstone-ng commented
Expect this to be released. Thank you all very much.

2024-10-07 06:55 UTC, vietstone-ng commented
@vallerydelexy  The bump is acceptable.
- First, it's from native, as @OutdatedGuy pointed out above (https://developers.google.com/ml-kit/release-notes#september_30_2024)
- Another reason may be iOS's privacy manifest, as old versions do not have it.

2024-10-07 17:12 UTC, poka-IT commented
I don't see any change log about septembre 2024 here: https://developers.google.com/ml-kit/release-notes#september_30_2024

Am I cross-eyed?

The bump is really hard...

2024-10-07 17:36 UTC, fbernaly approved these changes

2024-10-07 17:37 UTC, merged

2024-10-07 18:04 UTC, fbernaly commented
![Screenshot 2024-10-07 at 11 03 05 AM](https://github.com/user-attachments/assets/b025391c-2628-4352-933f-c537f444a489)